"""empty message

Revision ID: 65b7d24ec541
Revises: cfea5358542b
Create Date: 2017-10-20 09:45:01.020252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b7d24ec541'
down_revision = 'cfea5358542b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
