"""3

Revision ID: cfea5358542b
Revises: 596ddee1665b
Create Date: 2017-10-20 08:46:58.022097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfea5358542b'
down_revision = '596ddee1665b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('post_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    op.drop_column('tasks', 'post_time')
    # ### end Alembic commands ###
